import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type Dict = Record<string, unknown>;

const TOKENS_DIR = path.resolve(import.meta.dirname);
const THEME_DIR = path.resolve(TOKENS_DIR, "themes");
const MANIFEST_TS = path.resolve(TOKENS_DIR, "themes/manifest.ts");
const OUTPUT_UI_GLOBALS = path.resolve(
  TOKENS_DIR,
  "../ui/src/styles/globals.css",
);

function kebabify(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/\./g, "-")
    .toLowerCase();
}

function flatten(obj: Dict, prefix = ""): Dict {
  const out: Dict = {};
  for (const [key, value] of Object.entries(obj)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(out, flatten(value as Dict, nextKey));
    } else {
      out[nextKey] = value;
    }
  }
  return out;
}

function resolveRefs(value: unknown, lookup: Dict, seen = new Set<string>()): unknown {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, ref: string) => {
    if (seen.has(ref)) return `{${ref}}`;
    if (lookup[ref] !== undefined) {
      seen.add(ref);
      return asString(resolveRefs(lookup[ref], lookup, seen));
    }
    return `{${ref}}`;
  });
}

function readJson(file: string): Dict {
  return JSON.parse(readFileSync(file, "utf8"));
}

/** Theme/token JSON values must be strings; fail the build loudly otherwise. */
function asString(value: unknown): string {
  if (typeof value === "string") return value;
  throw new Error(
    `Expected string value, got ${typeof value}: ${String(value)}`,
  );
}


function toCssVars(map: Dict): string[] {
  return Object.entries(map).map(
    ([key, val]) => `  --sat-${kebabify(key)}: ${asString(val)};`,
  );
}

function buildBaseMap(): Dict {
  const base = readJson(path.join(TOKENS_DIR, "tokens", "base.json"));
  const semantic = readJson(path.join(TOKENS_DIR, "tokens", "semantic.json"));
  const component = readJson(path.join(TOKENS_DIR, "tokens", "component.json"));

  // Stage 1: base
  const baseFlat = flatten(base);
  const resolvedBase: Dict = {};
  for (const [k, v] of Object.entries(baseFlat)) {
    resolvedBase[k] = resolveRefs(v, baseFlat);
  }

  // Stage 2: semantic (may reference base)
  const semFlatRaw = flatten(semantic);
  const resolvedSem: Dict = {};
  for (const [k, v] of Object.entries(semFlatRaw)) {
    resolvedSem[k] = resolveRefs(v, { ...resolvedBase, ...semFlatRaw });
  }

  // Stage 3: component (may reference base+semantic)
  const compFlatRaw = flatten(component);
  const resolvedComp: Dict = {};
  for (const [k, v] of Object.entries(compFlatRaw)) {
    resolvedComp[k] = resolveRefs(v, {
      ...resolvedBase,
      ...resolvedSem,
      ...compFlatRaw,
    });
  }

  const combined = { ...resolvedBase, ...resolvedSem, ...resolvedComp };
  const final: Dict = {};
  for (const [k, v] of Object.entries(combined)) {
    final[k] = resolveRefs(v, combined);
  }

  return final;
}

type ThemeMeta = {
  id: string;
  label: string;
  mode?: string;
  description?: string;
};

type ThemeBuild = {
  meta: ThemeMeta;
  overrides: Dict;
};

function loadThemes(baseMap: Dict): ThemeBuild[] {
  const files = readdirSync(THEME_DIR).filter((f) => f.endsWith(".json"));
  return files.map((file) => {
    const full = path.join(THEME_DIR, file);
    const raw = readJson(full);
    const overridesFlat = flatten((raw.overrides as Dict) ?? {});
    const resolved: Dict = {};
    for (const [k, v] of Object.entries(overridesFlat)) {
      resolved[k] = resolveRefs(v, { ...baseMap, ...overridesFlat });
    }
    const meta: ThemeMeta = {
      id: asString(raw.id ?? ""),
      label: asString(raw.label ?? ""),
      mode: raw.mode === undefined ? undefined : asString(raw.mode),
      description:
        raw.description === undefined ? undefined : asString(raw.description),
    };
    return {
      meta,
      overrides: resolved,
    };
  });
}

function generateCss(baseMap: Dict, themes: ThemeBuild[]): string {
  const lines: string[] = [];
  lines.push("/* Generated by packages/ui/tokens/build.ts */");
  lines.push(":root {");
  lines.push(...toCssVars(baseMap));
  lines.push("  /* shadcn bridge vars */");
  lines.push("  --background: var(--sat-surface-1);");
  lines.push("  --foreground: var(--sat-text-primary);");
  lines.push("  --card: var(--sat-surface-2);");
  lines.push("  --card-foreground: var(--sat-text-primary);");
  lines.push("  --popover: var(--sat-surface-2);");
  lines.push("  --popover-foreground: var(--sat-text-primary);");
  lines.push("  --primary: var(--sat-accent-primary);");
  lines.push("  --primary-foreground: var(--sat-text-inverse);");
  lines.push("  --secondary: var(--sat-surface-3);");
  lines.push("  --secondary-foreground: var(--sat-text-primary);");
  lines.push("  --muted: var(--sat-surface-3);");
  lines.push("  --muted-foreground: var(--sat-text-muted);");
  lines.push("  --accent: var(--sat-editor-popover-active-bg);");
  lines.push("  --accent-foreground: var(--sat-editor-popover-active-text);");
  lines.push("  --destructive: var(--sat-state-danger);");
  lines.push("  --destructive-foreground: var(--sat-text-inverse);");
  lines.push("  --border: var(--sat-layout-border);");
  lines.push("  --input: var(--sat-layout-border);");
  lines.push("  --ring: var(--sat-control-focus-ring);");
  lines.push("  --radius: var(--sat-layout-radius-md);");
  lines.push("}");

  for (const theme of themes) {
    if (Object.keys(theme.overrides).length === 0) continue;
    const selector = `[data-theme="${theme.meta.id}"]`;
    lines.push("");
    lines.push(`${selector} {`);
    lines.push(...toCssVars(theme.overrides));
    lines.push("}");
  }

  return `${lines.join("\n")}\n`;
}


function generateManifest(themes: ThemeBuild[], defaultId: string): string {
  const ids = themes.map((t) => `"${t.meta.id}"`).join(" | ");
  const arr = themes
    .map(
      (t) =>
        `  { id: "${t.meta.id}", label: "${t.meta.label}", mode: "${
          t.meta.mode ?? "light"
        }", description: ${JSON.stringify(t.meta.description ?? "")} },`,
    )
    .join("\n");
  return `// Auto-generated by tokens/build.ts
export type ThemeId = ${ids};
  export type ThemeMode = string;
export interface ThemeMeta { id: ThemeId; label: string; mode: ThemeMode; description?: string; }
export const themes: ThemeMeta[] = [
${arr}
];
export const defaultThemeId: ThemeId = "${defaultId}";
`;
}

function main() {
  const baseMap = buildBaseMap();
  const themes = loadThemes(baseMap);
  const css = generateCss(baseMap, themes);
  writeFileSync(OUTPUT_UI_GLOBALS, css);
  const manifest = generateManifest(themes, "dark");
  writeFileSync(MANIFEST_TS, manifest);
  console.log(
    `Generated globals.css with ${Object.keys(baseMap).length} vars and ${themes.length} themes.`,
  );
}

main();
