[package]
name = "basalt-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
basalt-types = { path = "../basalt-types" }
basalt-parser = { path = "../basalt-parser" }
basalt-graph = { path = "../basalt-graph" }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
