// Auto-generated by tokens/build.ts
export type TokenName =
  | "sat-palette-surface1"
  | "sat-palette-surface2"
  | "sat-palette-surface3"
  | "sat-palette-text-primary"
  | "sat-palette-text-muted"
  | "sat-palette-text-inverse"
  | "sat-palette-accent"
  | "sat-palette-accent-strong"
  | "sat-palette-border"
  | "sat-palette-focus-ring"
  | "sat-palette-success"
  | "sat-palette-warning"
  | "sat-palette-danger"
  | "sat-palette-info"
  | "sat-palette-code-bg"
  | "sat-palette-code-muted"
  | "sat-palette-code-hover-bg"
  | "sat-palette-code-hover-text"
  | "sat-palette-heading7"
  | "sat-palette-popover-bg"
  | "sat-palette-popover-border"
  | "sat-palette-popover-text"
  | "sat-palette-popover-muted"
  | "sat-palette-popover-active-bg"
  | "sat-palette-popover-active-text"
  | "sat-palette-task-accent"
  | "sat-palette-code-keyword"
  | "sat-palette-code-string"
  | "sat-palette-code-number"
  | "sat-palette-code-comment"
  | "sat-palette-code-function"
  | "sat-palette-code-type"
  | "sat-palette-code-variable"
  | "sat-palette-code-operator"
  | "sat-radius-sm"
  | "sat-radius-md"
  | "sat-radius-lg"
  | "sat-radius-pill"
  | "sat-spacing-xs"
  | "sat-spacing-sm"
  | "sat-spacing-md"
  | "sat-spacing-lg"
  | "sat-spacing-xl"
  | "sat-shadow-sm"
  | "sat-shadow-md"
  | "sat-shadow-lg"
  | "sat-font-sans"
  | "sat-font-mono"
  | "sat-surface-1"
  | "sat-surface-2"
  | "sat-surface-3"
  | "sat-text-primary"
  | "sat-text-muted"
  | "sat-text-inverse"
  | "sat-accent-primary"
  | "sat-accent-strong"
  | "sat-editor-caret"
  | "sat-border-default"
  | "sat-state-success"
  | "sat-state-warning"
  | "sat-state-danger"
  | "sat-state-info"
  | "sat-focus-ring"
  | "sat-layout-surface-main"
  | "sat-layout-surface-raised"
  | "sat-layout-surface-card"
  | "sat-layout-border"
  | "sat-layout-divider"
  | "sat-layout-shadow-sm"
  | "sat-layout-shadow-md"
  | "sat-layout-shadow-lg"
  | "sat-layout-radius-sm"
  | "sat-layout-radius-md"
  | "sat-layout-radius-lg"
  | "sat-editor-background"
  | "sat-editor-font-size"
  | "sat-editor-line-height"
  | "sat-editor-readable-width"
  | "sat-editor-heading1"
  | "sat-editor-heading2"
  | "sat-editor-heading3"
  | "sat-editor-heading4"
  | "sat-editor-heading5"
  | "sat-editor-heading6"
  | "sat-editor-heading7"
  | "sat-editor-title-size"
  | "sat-editor-title-weight"
  | "sat-editor-title-line-height"
  | "sat-editor-title-letter-spacing"
  | "sat-editor-section-label-color"
  | "sat-editor-section-label-size"
  | "sat-editor-section-label-weight"
  | "sat-editor-property-key-color"
  | "sat-editor-property-value-color"
  | "sat-editor-property-empty-color"
  | "sat-editor-property-icon-color"
  | "sat-editor-property-icon-size"
  | "sat-editor-property-key-width"
  | "sat-editor-property-row-height"
  | "sat-editor-property-gap"
  | "sat-editor-property-title-gap"
  | "sat-editor-property-label-gap"
  | "sat-editor-property-body-gap"
  | "sat-editor-property-hover-background"
  | "sat-editor-property-hover-border"
  | "sat-editor-property-focus-ring"
  | "sat-editor-accent"
  | "sat-editor-inline-bg"
  | "sat-editor-hr"
  | "sat-editor-blockquote-border"
  | "sat-editor-blockquote-text"
  | "sat-editor-code-bg"
  | "sat-editor-code-muted"
  | "sat-editor-code-hover-bg"
  | "sat-editor-code-hover-text"
  | "sat-editor-popover-bg"
  | "sat-editor-popover-border"
  | "sat-editor-popover-text"
  | "sat-editor-popover-muted"
  | "sat-editor-popover-active-bg"
  | "sat-editor-popover-active-text"
  | "sat-editor-task-accent"
  | "sat-graph-background"
  | "sat-graph-node"
  | "sat-graph-tag"
  | "sat-graph-attachment"
  | "sat-graph-edge"
  | "sat-graph-label"
  | "sat-graph-hover-fill"
  | "sat-graph-hover-ring"
  | "sat-graph-hover-edge"
  | "sat-syntax-keyword"
  | "sat-syntax-string"
  | "sat-syntax-number"
  | "sat-syntax-comment"
  | "sat-syntax-function"
  | "sat-syntax-type"
  | "sat-syntax-variable"
  | "sat-syntax-operator"
  | "sat-syntax-atom"
  | "sat-syntax-property"
  | "sat-syntax-tag"
  | "sat-syntax-attribute"
  | "sat-syntax-punctuation"
  | "sat-syntax-regexp"
  | "sat-syntax-doc"
  | "sat-syntax-macro"
  | "sat-syntax-meta"
  | "sat-syntax-link"
  | "sat-syntax-changed"
  | "sat-syntax-deleted"
  | "sat-syntax-inserted"
  | "sat-control-focus-ring";
export const tokenNames: TokenName[] = [
  "sat-palette-surface1",
  "sat-palette-surface2",
  "sat-palette-surface3",
  "sat-palette-text-primary",
  "sat-palette-text-muted",
  "sat-palette-text-inverse",
  "sat-palette-accent",
  "sat-palette-accent-strong",
  "sat-palette-border",
  "sat-palette-focus-ring",
  "sat-palette-success",
  "sat-palette-warning",
  "sat-palette-danger",
  "sat-palette-info",
  "sat-palette-code-bg",
  "sat-palette-code-muted",
  "sat-palette-code-hover-bg",
  "sat-palette-code-hover-text",
  "sat-palette-heading7",
  "sat-palette-popover-bg",
  "sat-palette-popover-border",
  "sat-palette-popover-text",
  "sat-palette-popover-muted",
  "sat-palette-popover-active-bg",
  "sat-palette-popover-active-text",
  "sat-palette-task-accent",
  "sat-palette-code-keyword",
  "sat-palette-code-string",
  "sat-palette-code-number",
  "sat-palette-code-comment",
  "sat-palette-code-function",
  "sat-palette-code-type",
  "sat-palette-code-variable",
  "sat-palette-code-operator",
  "sat-radius-sm",
  "sat-radius-md",
  "sat-radius-lg",
  "sat-radius-pill",
  "sat-spacing-xs",
  "sat-spacing-sm",
  "sat-spacing-md",
  "sat-spacing-lg",
  "sat-spacing-xl",
  "sat-shadow-sm",
  "sat-shadow-md",
  "sat-shadow-lg",
  "sat-font-sans",
  "sat-font-mono",
  "sat-surface-1",
  "sat-surface-2",
  "sat-surface-3",
  "sat-text-primary",
  "sat-text-muted",
  "sat-text-inverse",
  "sat-accent-primary",
  "sat-accent-strong",
  "sat-editor-caret",
  "sat-border-default",
  "sat-state-success",
  "sat-state-warning",
  "sat-state-danger",
  "sat-state-info",
  "sat-focus-ring",
  "sat-layout-surface-main",
  "sat-layout-surface-raised",
  "sat-layout-surface-card",
  "sat-layout-border",
  "sat-layout-divider",
  "sat-layout-shadow-sm",
  "sat-layout-shadow-md",
  "sat-layout-shadow-lg",
  "sat-layout-radius-sm",
  "sat-layout-radius-md",
  "sat-layout-radius-lg",
  "sat-editor-background",
  "sat-editor-font-size",
  "sat-editor-line-height",
  "sat-editor-readable-width",
  "sat-editor-heading1",
  "sat-editor-heading2",
  "sat-editor-heading3",
  "sat-editor-heading4",
  "sat-editor-heading5",
  "sat-editor-heading6",
  "sat-editor-heading7",
  "sat-editor-title-size",
  "sat-editor-title-weight",
  "sat-editor-title-line-height",
  "sat-editor-title-letter-spacing",
  "sat-editor-section-label-color",
  "sat-editor-section-label-size",
  "sat-editor-section-label-weight",
  "sat-editor-property-key-color",
  "sat-editor-property-value-color",
  "sat-editor-property-empty-color",
  "sat-editor-property-icon-color",
  "sat-editor-property-icon-size",
  "sat-editor-property-key-width",
  "sat-editor-property-row-height",
  "sat-editor-property-gap",
  "sat-editor-property-title-gap",
  "sat-editor-property-label-gap",
  "sat-editor-property-body-gap",
  "sat-editor-property-hover-background",
  "sat-editor-property-hover-border",
  "sat-editor-property-focus-ring",
  "sat-editor-accent",
  "sat-editor-inline-bg",
  "sat-editor-hr",
  "sat-editor-blockquote-border",
  "sat-editor-blockquote-text",
  "sat-editor-code-bg",
  "sat-editor-code-muted",
  "sat-editor-code-hover-bg",
  "sat-editor-code-hover-text",
  "sat-editor-popover-bg",
  "sat-editor-popover-border",
  "sat-editor-popover-text",
  "sat-editor-popover-muted",
  "sat-editor-popover-active-bg",
  "sat-editor-popover-active-text",
  "sat-editor-task-accent",
  "sat-graph-background",
  "sat-graph-node",
  "sat-graph-tag",
  "sat-graph-attachment",
  "sat-graph-edge",
  "sat-graph-label",
  "sat-graph-hover-fill",
  "sat-graph-hover-ring",
  "sat-graph-hover-edge",
  "sat-syntax-keyword",
  "sat-syntax-string",
  "sat-syntax-number",
  "sat-syntax-comment",
  "sat-syntax-function",
  "sat-syntax-type",
  "sat-syntax-variable",
  "sat-syntax-operator",
  "sat-syntax-atom",
  "sat-syntax-property",
  "sat-syntax-tag",
  "sat-syntax-attribute",
  "sat-syntax-punctuation",
  "sat-syntax-regexp",
  "sat-syntax-doc",
  "sat-syntax-macro",
  "sat-syntax-meta",
  "sat-syntax-link",
  "sat-syntax-changed",
  "sat-syntax-deleted",
  "sat-syntax-inserted",
  "sat-control-focus-ring",
];
