// Auto-generated by tokens/build.ts
export type ThemeId =
  | "solarized-light"
  | "catppuccin-mocha"
  | "dracula"
  | "light"
  | "solarized-dark"
  | "dark"
  | "catppuccin-latte";
export type ThemeMode = "light" | "dark" | string;
export interface ThemeMeta {
  id: ThemeId;
  label: string;
  mode: ThemeMode;
  description?: string;
}
export const themes: ThemeMeta[] = [
  {
    id: "solarized-light",
    label: "Solarized Light",
    mode: "light",
    description: "Ethan Schoonover's Solarized light palette.",
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    mode: "dark",
    description: "Catppuccin cozy dark variant.",
  },
  {
    id: "dracula",
    label: "Dracula",
    mode: "dark",
    description: "Dracula classic dark purple.",
  },
  {
    id: "light",
    label: "Light",
    mode: "light",
    description: "Bright neutral light theme.",
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    mode: "dark",
    description: "Solarized dark palette.",
  },
  {
    id: "dark",
    label: "Dark",
    mode: "dark",
    description: "Baseline dark theme for Basalt.",
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    mode: "light",
    description: "Catppuccin pastel light variant.",
  },
];
export const defaultThemeId: ThemeId = "dark";
