#!/usr/bin/env bash
# Rebuild the graph force-layout WebAssembly (crates/graph-wasm) and copy it
# into the frontend graph feature.
#
# The committed apps/tauri/src/features/graph/components/graph_sim.wasm is
# GENERATED by this script — never hand-edit it. Run `bun run build:wasm`
# after changing the graph Rust (basalt-graph / graph-wasm).
set -euo pipefail

cd "$(dirname "$0")/../crates/graph-wasm"
echo "Building graph-wasm for wasm32-unknown-unknown (release)…"
cargo build --target wasm32-unknown-unknown --release

SRC=$(find target/wasm32-unknown-unknown/release -maxdepth 1 -name '*.wasm' | head -n1)
if [ -z "$SRC" ]; then
  echo "error: no .wasm produced by build" >&2
  exit 1
fi

DEST=../../apps/tauri/src/features/graph/components/graph_sim.wasm
cp "$SRC" "$DEST"
echo "Copied $(basename "$SRC") -> $DEST"
