#!/usr/bin/env bash
# Rebuild the frontmatter engine WebAssembly (crates/basalt-wasm/frontmatter-wasm)
# and copy it into the frontend editor feature.
#
# The committed apps/tauri/src/features/editor/components/frontmatter.wasm is
# GENERATED by this script — never hand-edit it. Run `bun run build:wasm`
# after changing the frontmatter Rust (basalt-parser / basalt-types).
set -euo pipefail

cd "$(dirname "$0")/../crates/basalt-wasm/frontmatter-wasm"
echo "Building frontmatter-wasm for wasm32-unknown-unknown (release)…"
cargo build --target wasm32-unknown-unknown --release

SRC=$(find target/wasm32-unknown-unknown/release -maxdepth 1 -name '*.wasm' | head -n1)
if [ -z "$SRC" ]; then
  echo "error: no .wasm produced by build" >&2
  exit 1
fi

DEST=../../../apps/tauri/src/features/editor/components/frontmatter.wasm
mkdir -p "$(dirname "$DEST")"
cp "$SRC" "$DEST"
echo "Copied $(basename "$SRC") -> $DEST"