import {
  IconArrowLeft,
  IconBook,
  IconCalendarEvent,
  IconCalendarOff,
  IconCheckbox,
  IconFilePlus,
  IconFileSearch,
  IconFlag,
  IconFolderOpen,
  IconGauge,
  IconLayoutBoardSplit,
  IconLayoutNavbar,
  IconLayoutSidebarRight,
  IconPencil,
  IconPinned,
  IconPlus,
  IconPrinter,
  IconRectangleVertical,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSitemap,
  IconTemplate,
  IconTrash,
  IconX,
} from "@tabler/icons-react";
import type { ComponentType } from "react";
const ICONS: Record<string, ComponentType<{ size?: number }>> = {
  IconArrowLeft,
  IconBook,
  IconCalendarEvent,
  IconCalendarOff,
  IconCheckbox,
  IconFilePlus,
  IconFileSearch,
  IconFlag,
  IconFolderOpen,
  IconGauge,
  IconLayoutBoardSplit,
  IconLayoutNavbar,
  IconLayoutSidebarRight,
  IconPencil,
  IconPinned,
  IconPlus,
  IconPrinter,
  IconRectangleVertical,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSitemap,
  IconTemplate,
  IconTrash,
  IconX,
};

export function resolveIcon(
  name: string | undefined,
): ComponentType<{ size?: number }> | undefined {
  return name ? ICONS[name] : undefined;
}
