import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type Dict = Record<string, unknown>;

const TOKENS_DIR = path.resolve(import.meta.dirname);
const THEME_DIR = path.resolve(TOKENS_DIR, "../theme");
const STYLES_DIR = path.resolve(TOKENS_DIR, "../src/styles");
const OUTPUT_CSS = path.join(STYLES_DIR, "globals.css");
const OUTPUT_TYPES = path.join(STYLES_DIR, "tokens.d.ts");
const MANIFEST_TS = path.resolve(TOKENS_DIR, "../theme/manifest.ts");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function kebabify(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/\./g, "-")
    .toLowerCase();
}

function flatten(obj: Dict, prefix = ""): Dict {
  const out: Dict = {};
  for (const [key, value] of Object.entries(obj)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(out, flatten(value, nextKey));
    } else {
      out[nextKey] = value;
    }
  }
  return out;
}

function resolveRefs(value: unknown, lookup: Dict): unknown {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    if (lookup[ref] !== undefined) return String(lookup[ref]);
    return value;
  });
}

function readJson(file: string): Dict {
  return JSON.parse(readFileSync(file, "utf8"));
}

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

function toCssVars(map: Dict): string[] {
  return Object.entries(map).map(
    ([key, val]) => `  --sat-${kebabify(key)}: ${val};`,
  );
}

// ---------------------------------------------------------------------------
// Build pipeline
// ---------------------------------------------------------------------------

function buildBaseMap(): Dict {
  const base = readJson(path.join(TOKENS_DIR, "base.json"));
  const semantic = readJson(path.join(TOKENS_DIR, "semantic.json"));
  const component = readJson(path.join(TOKENS_DIR, "component.json"));

  // Stage 1: base
  const baseFlat = flatten(base);
  const resolvedBase: Dict = {};
  for (const [k, v] of Object.entries(baseFlat)) {
    resolvedBase[k] = resolveRefs(v, baseFlat);
  }

  // Stage 2: semantic (may reference base)
  const semFlatRaw = flatten(semantic);
  const resolvedSem: Dict = {};
  for (const [k, v] of Object.entries(semFlatRaw)) {
    resolvedSem[k] = resolveRefs(v, { ...resolvedBase, ...semFlatRaw });
  }

  // Stage 3: component (may reference base+semantic)
  const compFlatRaw = flatten(component);
  const resolvedComp: Dict = {};
  for (const [k, v] of Object.entries(compFlatRaw)) {
    resolvedComp[k] = resolveRefs(v, {
      ...resolvedBase,
      ...resolvedSem,
      ...compFlatRaw,
    });
  }

  const combined = { ...resolvedBase, ...resolvedSem, ...resolvedComp };
  const final: Dict = {};
  for (const [k, v] of Object.entries(combined)) {
    final[k] = resolveRefs(v, combined);
  }

  return final;
}

type ThemeMeta = {
  id: string;
  label: string;
  mode?: string;
  description?: string;
};

type ThemeBuild = {
  meta: ThemeMeta;
  overrides: Dict;
};

function loadThemes(baseMap: Dict): ThemeBuild[] {
  const files = readdirSync(THEME_DIR).filter((f) => f.endsWith(".json"));
  return files.map((file) => {
    const full = path.join(THEME_DIR, file);
    const raw = readJson(full);
    const overridesFlat = flatten(raw.overrides as Dict ?? {});
    const resolved: Dict = {};
    for (const [k, v] of Object.entries(overridesFlat)) {
      resolved[k] = resolveRefs(v, { ...baseMap, ...overridesFlat });
    }
    const meta: ThemeMeta = {
      id: String(raw.id ?? ""),
      label: String(raw.label ?? ""),
      mode: raw.mode ? String(raw.mode) : undefined,
      description: raw.description ? String(raw.description) : undefined,
    };
    return {
      meta,
      overrides: resolved,
    };
  });
}

function generateCss(baseMap: Dict, themes: ThemeBuild[]): string {
  const lines: string[] = [];
  lines.push("/* Generated by packages/ui/tokens/build.ts */");
  lines.push(":root {");
  lines.push(...toCssVars(baseMap));
  lines.push("  /* shadcn bridge vars */");
  lines.push("  --background: var(--sat-surface-1);");
  lines.push("  --foreground: var(--sat-text-primary);");
  lines.push("  --card: var(--sat-surface-2);");
  lines.push("  --card-foreground: var(--sat-text-primary);");
  lines.push("  --popover: var(--sat-surface-2);");
  lines.push("  --popover-foreground: var(--sat-text-primary);");
  lines.push("  --primary: var(--sat-accent-primary);");
  lines.push("  --primary-foreground: var(--sat-text-inverse);");
  lines.push("  --secondary: var(--sat-surface-3);");
  lines.push("  --secondary-foreground: var(--sat-text-primary);");
  lines.push("  --muted: var(--sat-surface-3);");
  lines.push("  --muted-foreground: var(--sat-text-muted);");
  lines.push("  --accent: var(--sat-surface-3);");
  lines.push("  --accent-foreground: var(--sat-text-primary);");
  lines.push("  --destructive: var(--sat-state-danger);");
  lines.push("  --destructive-foreground: var(--sat-text-inverse);");
  lines.push("  --border: var(--sat-layout-border);");
  lines.push("  --input: var(--sat-layout-border);");
  lines.push("  --ring: var(--sat-control-focus-ring);");
  lines.push("  --radius: var(--sat-layout-radius-md);");
  lines.push("}");

  for (const theme of themes) {
    const selector = `[data-theme="${theme.meta.id}"]`;
    lines.push("");
    lines.push(`${selector} {`);
    lines.push(...toCssVars(theme.overrides));
    lines.push("}");
  }

  return `${lines.join("\n")}\n`;
}

function generateTypes(baseMap: Dict): string {
  const keys = Object.keys(baseMap)
    .map((k) => `"sat-${kebabify(k)}"`)
    .join(" | ");
  return `// Auto-generated by tokens/build.ts\nexport type TokenName = ${keys};\nexport const tokenNames: TokenName[] = [${Object.keys(
    baseMap,
  )
    .map((k) => `"sat-${kebabify(k)}"`)
    .join(", ")}];\n`;
}

function generateManifest(themes: ThemeBuild[], defaultId: string): string {
  const ids = themes.map((t) => `"${t.meta.id}"`).join(" | ");
  const arr = themes
    .map(
      (t) =>
        `  { id: "${t.meta.id}", label: "${t.meta.label}", mode: "${t.meta.mode ?? "light"
        }", description: ${JSON.stringify(t.meta.description ?? "")} },`,
    )
    .join("\n");
  return `// Auto-generated by tokens/build.ts
export type ThemeId = ${ids};
export type ThemeMode = "light" | "dark" | string;
export interface ThemeMeta { id: ThemeId; label: string; mode: ThemeMode; description?: string; }
export const themes: ThemeMeta[] = [
${arr}
];
export const defaultThemeId: ThemeId = "${defaultId}";
`;
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

function main() {
  ensureDir(STYLES_DIR);
  const baseMap = buildBaseMap();
  const themes = loadThemes(baseMap);
  const css = generateCss(baseMap, themes);
  writeFileSync(OUTPUT_CSS, css);
  writeFileSync(OUTPUT_TYPES, generateTypes(baseMap));
  const manifest = generateManifest(themes, "dark");
  writeFileSync(MANIFEST_TS, manifest);
  console.log(
    `Generated ${OUTPUT_CSS} with ${Object.keys(baseMap).length} vars and ${themes.length} themes.`,
  );
}

main();
